var htzzzInfo = {
    width: 8646.368164,
   height: 8646.368164,
   boundsW: -256,
   boundsH: 256,
   centerX: 67177.750000,
   centerY: 126823.210938,
   minZoom: 1,
   initZoom: 1,
   maxZoom: 3,
   bj: 128,
   initX: -105,
   initY: 130,
}
var selectRegion_htzzz = [
   {
       name: '阿萨拉 基地',
       x: "65556.000000",
       y: "-120633.000000",
   },
   {
       name: '阿萨拉 茶水间',
       x: "66568.000000",
       y: "-122926.000000",
   },
   {
       name: 'A区 停车场',
       x: "68492.000000",
       y: "-121616.000000",
   },
   {
       name: 'A区 破墙',
       x: "68460.000000",
       y: "-124092.000000",
   },
   {
       name: 'A区 货物堆放场',
       x: "70796.000000",
       y: "-125456.000000",
   },
   {
       name: 'A区 运输通道',
       x: "72508.000000",
       y: "-127604.000000",
   },
   {
       name: 'A区 更衣室',
       x: "70708.000000",
       y: "-128580.000000",
   },
   {
       name: 'A区 长廊',
       x: "69562.140625",
       y: "-127761.882812",
   },
   {
       name: '中路 桥',
       x: "67166.140625",
       y: "-126945.882812",
   },
   {
       name: '中路 后侧',
       x: "66910.140625",
       y: "-125161.882812",
   },
   {
       name: '中路 前侧',
       x: "66630.140625",
       y: "-131817.875000",
   },
   {
       name: '中路 储藏室',
       x: "68894.140625",
       y: "-129721.875000",
   },
   {
       name: '哈夫克 闸口',
       x: "66678.140625",
       y: "-133897.875000",
   },
   {
    name: '中路 控制室',
    x: "65042.140625",
    y: "-130425.875000",
},
{
    name: 'B区 检修通道',
    x: "62050.140625",
    y: "-130841.875000",
},
{
    name: 'B区 发电区',
    x: "62530.140625",
    y: "-126785.875000",
},
{
    name: 'B区 闸门',
    x: "64914.140625",
    y: "-127621.875000",
},
{
    name: 'B区 外场',
    x: "62882.140625",
    y: "-122657.875000",
},
{
    name: '中路 B侧路',
    x: "65116.140625",
    y: "-124079.882812",
},
];

// 默认显示的区域文字锚点，结构与常规地图的 selectRegion_* 一致。
var selectPoint_htzzz = [
    {
        "type": "normal",
        "name": "区域点位",
        "point_name": "中路桥",
        "icon": "icon_csd",
        "img": "htzzz_zl",
        "x": "67066.036",
        "y": "-127288.37",
    },
    {
        "type": "normal",
        "name": "区域点位",
        "point_name": "B点",
        "icon": "icon_csd",
        "img": "htzzz_b",
        "x": "64138",
        "y": "-129795",
    },
    {
        "type": "normal",
        "name": "区域点位",
        "point_name": "A点",
        "icon": "icon_csd",
        "img": "htzzz_a",
        "x": "71803",
        "y": "-129659",
    },
    {
        "type": "normal",
        "name": "区域点位",
        "point_name": "防守方出生点",
        "icon": "icon_csd",
        "img": "htzzz_ff",
        "x": "66570",
        "y": "-134355",
    },
    {
        "type": "normal",
        "name": "区域点位",
        "point_name": "进攻方出生点",
        "icon": "icon_csd",
        "img": "htzzz_gf",
        "x": "65523",
        "y": "-120068",
    },
    {
        "type": "normal",
        "name": "灭火器",
        "point_name": "灭火器",
        "icon": "icon_mhq",
        "img": "htzzz_mhq1",
        "x": "68360",
        "y": "-127465",
    },
    {
        "type": "normal",
        "name": "灭火器",
        "point_name": "灭火器",
        "icon": "icon_mhq",
        "img": "htzzz_mhq2",
        "x": "67279",
        "y": "-128883",
    },
    
    {
        "type": "role",
        "name": "露娜",
        "icon": "icon_ln",
        "points": [
            {
                "name": "",
                "point_name": "侦察箭矢",
                "point_desc": "",
                "camp": "进攻",
                "icon": "icon_zcjs",
                "vid":"",
                "price": "",
                "x": "",
                "y":"",
                "role_x": "",
                "role_y": ""
            },
            {
                "name": "",
                "point_name": "电击箭矢",
                "point_desc": "",
                "camp": "进攻",
                "icon": "icon_djjs",
                "vid":"",
                "price": "",
                "x": "",
                "y":"",
                "role_x": "",
                "role_y": ""
            },
            {
                "name": "中路排点炸烟雷",
                "point_name": "增强型破片手雷",
                "point_desc": "在停车场白车前根据小地图落点调整准星，可精准炸掉中路灭火器",
                "camp": "进攻",
                "icon": "icon_sld",
                "vid":"r1288bl7pj1",
                "price": "250",
                "x": "66937",
                "y":"-128925",
                "role_x": "69453",
                "role_y": "-121815"
            },
            {
                "name": "",
                "point_name": "敌情追踪",
                "point_desc": "",
                "camp": "进攻",
                "icon": "icon_dqzz",
                "vid":"",
                "price": "",
                "x": "",
                "y":"",
                "role_x": "",
                "role_y": ""
            },
            {
                "name": "",
                "point_name": "侦察箭矢",
                "point_desc": "",
                "camp": "防守",
                "icon": "icon_zcjs",
                "vid":"",
                "price": "",
                "x": "",
                "y":"",
                "role_x": "",
                "role_y": ""
            },
            {
                "name": "A区大门电箭防守",
                "point_name": "电击箭矢",
                "point_desc": "瞄准白色箱左侧反弹蓄满射出电箭，防守A大门",
                "camp": "防守",
                "icon": "icon_djjs",
                "vid":"o1288h475sc",
                "price": "200",
                "x": "70101.031",
                "y":"-125218.153",
                "role_x": "72263.941",
                "role_y": "-126728.351"
            },
            {
                "name": "控制室电箭防守",
                "point_name": "电击箭矢",
                "point_desc": "B2楼控制室贴紧控制台，瞄准窗框反弹蓄满射出，防止B小压出",
                "camp": "防守",
                "icon": "icon_djjs",
                "vid":"j1288qjywyb",
                "price": "200",
                "x": "64147",
                "y":"-129408",
                "role_x": "63827",
                "role_y": "-129398"
            },
            
            {
                "name": "A点远距离手雷",
                "point_name": "增强型破片手雷",
                "point_desc": "在A二楼平台白箱后，瞄准天花板下端投掷手雷，对集装箱后敌人造成伤害",
                "camp": "防守",
                "icon": "icon_sld",
                "vid":"q1288hv8218",
                "price": "250",
                "x": "71872",
                "y":"-124290",
                "role_x": "72683",
                "role_y": "-130809"
            },
            {
                "name": "",
                "point_name": "敌情追踪",
                "point_desc": "",
                "camp": "防守",
                "icon": "icon_dqzj",
                "vid":"",
                "price": "",
                "x": "",
                "y":"",
                "role_x": "",
                "role_y": ""
            },
        ]
    },
    {
        "type": "role",
        "name": "威龙",
        "icon": "icon_wl",
        "points": [
            {
                "name": "A区抛射虎蹲炮",
                "point_name": "虎蹲炮",
                "point_desc": "白箱上瞄准所示位置，防止防守方从A大门压出",
                "camp": "进攻",
                "icon": "icon_hdd",
                "vid": "n1288pj9smn",
                "price": "",
                "x": "72045.45",
                "y":"-126446.339",
                "role_x": "68677.329",
                "role_y": "-123348.499"
            },
            {
                "name": "",
                "point_name": "动力推进",
                "point_desc": "",
                "camp": "进攻",
                "icon": "icon_dltj",
                "vid":"",
                "price": "",
                "x": "",
                "y":"",
                "role_x": "",
                "role_y": ""
            },
            {
                "name": "",
                "point_name": "反坦克磁吸炸弹",
                "point_desc": "",
                "camp": "进攻",
                "icon": "icon_cxzd",
                "vid":"",
                "price": "",
                "x": "",
                "y":"",
                "role_x": "",
                "role_y": ""
            },
            {
                "name": "",
                "point_name": "单兵动力辅助系统",
                "point_desc": "",
                "camp": "进攻",
                "icon": "icon_fzxt",
                "vid":"",
                "price": "",
                "x": "",
                "y":"",
                "role_x": "",
                "role_y": ""
            },
            {
                "name": "B区抛射虎蹲炮",
                "point_name": "虎蹲炮",
                "point_desc": "贴墙使用虎蹲准星下方对准集装箱，瞄准电线杆，控制前往B大的敌人",
                "camp": "防守",
                "icon": "icon_hdd",
                "vid": "w1288xmvj4h",
                "price": "",
                "x": "62045.04",
                "y":"-126383.967",
                "role_x": "62772.72",
                "role_y": "-128754.127"
            },
           
            {
                "name": "威龙喷气跳桥位",
                "point_name": "动力推进",
                "point_desc": "防守侧跳跃推进可直接到达中路桥上",
                "camp": "防守",
                "icon": "icon_dltj",
                "vid": "f1288gkq843",
                "price": "200",
                "x": "67391.768",
                "y":"-127325.666",
                "role_x": "66651.413",
                "role_y": "-128758.612"
            },
            {
                "name": "",
                "point_name": "反坦克磁吸炸弹",
                "point_desc": "",
                "camp": "防守",
                "icon": "icon_cxzd",
                "vid":"",
                "price": "",
                "x": "",
                "y":"",
                "role_x": "",
                "role_y": ""
            },
            {
                "name": "",
                "point_name": "单兵动力辅助系统",
                "point_desc": "",
                "camp": "防守",
                "icon": "icon_fzxt",
                "vid":"",
                "price": "",
                "x": "",
                "y":"",
                "role_x": "",
                "role_y": ""
            },
        ]
    },
    {
        "type": "role",
        "name": "红狼",
        "icon": "icon_hl",
        "points": [
            {
                "name": "",
                "point_name": "超载模式",
                "point_desc": "",
                "camp": "进攻",
                "icon": "icon_czms",
                "vid":"",
                "price": "",
                "x": "",
                "y":"",
                "role_x": "",
                "role_y": ""
            },
            {
                "name": "中路排点炸烟手炮",
                "point_name": "三联装手炮",
                "point_desc": "沿垃圾桶右挪，瞄准电线杆所示位置发射手炮，可炸开中路烟",
                "camp": "进攻",
                "icon": "icon_slzsp",
                "vid": "o1288ruiuie",
                "price": "250",
                "x": "66941",
                "y":"-128883",
                "role_x": "66806",
                "role_y": "-123311"
            },
            {
                "name": "中路前侧干扰烟",
                "point_name": "突破型烟雾弹",
                "point_desc": "A点破败墙角处，瞄准天空时看小地图落点投掷出守方中路烟",
                "camp": "进攻",
                "icon": "icon_ywd",
                "vid": "k1288kh87kt",
                "price": "150",
                "x": "66164.50",
                "y":"-131484",
                "role_x": "68190.996",
                "role_y": "-124222.546"
            },
            {
                "name": "",
                "point_name": "战术滑铲",
                "point_desc": "",
                "camp": "进攻",
                "icon": "icon_zshc",
                "vid":"",
                "price": "",
                "x": "",
                "y":"",
                "role_x": "",
                "role_y": ""
            },
        ]
    },
    {
        "type": "role",
        "name": "乌鲁鲁",
        "icon": "icon_wll",
        "points": [
            {
                "name": "",
                "point_name": "复合制导巡飞弹",
                "point_desc": "",
                "camp": "进攻",
                "icon": "icon_dxfd",
                "vid":"",
                "price": "",
                "x": "",
                "y":"",
                "role_x": "",
                "role_y": ""
            },
            {
                "name": "",
                "point_name": "速凝掩体",
                "point_desc": "",
                "camp": "进攻",
                "icon": "icon_snyt",
                "vid":"",
                "price": "",
                "x": "",
                "y":"",
                "role_x": "",
                "role_y": ""
            },
            {
                "name": "燃烧弹压制B大门",
                "point_name": "复合型燃烧弹",
                "point_desc": "集装箱上投掷，压制B点防守方闪击",
                "camp": "进攻",
                "icon": "icon_fhrsd",
                "vid": "h1288ap8azf",
                "price": "300",
                "x": "62685.692",
                "y":"-128782.154",
                "role_x": "62719.466",
                "role_y": "-122668.901"
            },
            {
                "name": "燃烧弹压制A大门",
                "point_name": "复合型燃烧弹",
                "point_desc": "停车场角落投掷，压制A点防守方闪击",
                "camp": "进攻",
                "icon": "icon_fhrsd",
                "vid": "j1288cptwhb",
                "price": "300",
                "x": "72075.822",
                "y":"-126732.372",
                "role_x": "68704.729",
                "role_y": "-123326.249"
            },
            {
                "name": "",
                "point_name": "高分子防护材料",
                "point_desc": "",
                "camp": "进攻",
                "icon": "icon_fhcl",
                "vid":"",
                "price": "",
                "x": "",
                "y":"",
                "role_x": "",
                "role_y": ""
            },
        ]
    },
    {
        "type": "role",
        "name": "液氮",
        "icon": "icon_yd",
        "points": [
            {
                "name": "",
                "point_name": "液氮榴弹发射器",
                "point_desc": "",
                "camp": "进攻",
                "icon": "icon_ldfsq",
                "vid":"",
                "price": "",
                "x": "",
                "y":"",
                "role_x": "",
                "role_y": ""
            },
            {
                "name": "冷罐压制B大门",
                "point_name": "杜瓦冷罐",
                "point_desc": "集装箱上投掷，压制B点防守方闪击",
                "camp": "进攻",
                "icon": "icon_dwlg",
                "vid": "v1288docplv",
                "price": "300",
                "x": "62685.692",
                "y":"-128782.154",
                "role_x": "62719.466",
                "role_y": "-122668.901"
            },
            {
                "name": "冷罐压制A大门",
                "point_name": "杜瓦冷罐",
                "point_desc": "停车场角落投掷，压制A点防守方闪击",
                "camp": "进攻",
                "icon": "icon_dwlg",
                "vid": "e1288685w6k",
                "price": "300",
                "x": "72075.822",
                "y":"-126732.372",
                "role_x": "68704.729",
                "role_y": "-123326.249"
            },
            {
                "name": "",
                "point_name": "智能震撼弹",
                "point_desc": "",
                "camp": "进攻",
                "icon": "icon_znzhd",
                "vid":"",
                "price": "",
                "x": "",
                "y":"",
                "role_x": "",
                "role_y": ""
            },
            {
                "name": "",
                "point_name": "被动：冰冻",
                "point_desc": "",
                "camp": "进攻",
                "icon": "icon_bd",
                "vid":"",
                "price": "",
                "x": "",
                "y":"",
                "role_x": "",
                "role_y": ""
            },
        ]
    },
    {
        "type": "role",
        "name": "蜂医",
        "icon": "icon_fy",
        "points": [
            {
                "name": "",
                "point_name": "激素枪",
                "point_desc": "",
                "camp": "进攻",
                "icon": "icon_jsq",
                "vid":"",
                "price": "",
                "x": "",
                "y":"",
                "role_x": "",
                "role_y": ""
            },
            {
                "name": "",
                "point_name": "烟幕",
                "point_desc": "",
                "camp": "进攻",
                "icon": "icon_ym",
                "vid":"",
                "price": "",
                "x": "",
                "y":"",
                "role_x": "",
                "role_y": ""
            },
            {
                "name": "A点烟雾二层后门",
                "point_name": "蜂巢科技烟雾弹",
                "point_desc": "进攻A点，烟雾干扰A点二层敌人架枪",
                "camp": "进攻",
                "icon": "icon_fckjywd",
                "vid": "t12881a67jm",
                "price": "200",
                "x": "71906.233",
                "y":"-128697.717",
                "role_x": "71973.782",
                "role_y": "-127160.96"
            },
            {
                "name": "A点烟雾二层侧门",
                "point_name": "蜂巢科技烟雾弹",
                "point_desc": "进攻A点，烟雾干扰门口二层敌人架枪",
                "camp": "进攻",
                "icon": "icon_fckjywd",
                "vid": "a1288yf1bhl",
                "price": "200",
                "x": "71594.277",
                "y":"-128617.237",
                "role_x": "72438.649",
                "role_y": "-125949.022"
            },
            {
                "name": "A点烟雾二层掩体",
                "point_name": "蜂巢科技烟雾弹",
                "point_desc": "进攻A点，烟雾干扰二层箱子后敌人架枪",
                "camp": "进攻",
                "icon": "icon_fckjywd",
                "vid": "p1288uq9fcr",
                "price": "200",
                "x": "72354.211",
                "y":"-130711.28",
                "role_x": "72151.562",
                "role_y": "-128245.714"
            },
            {
                "name": "",
                "point_name": "高效救援",
                "point_desc": "",
                "camp": "进攻",
                "icon": "icon_gxjy",
                "vid":"",
                "price": "",
                "x": "",
                "y":"",
                "role_x": "",
                "role_y": ""
            },
        ]
    },
];
