var zhLang = {
    'lang1': '任务简报',
    'lang2': '任务地图',
    'lang3': '2023年8月22日',
    'lang4': '德国，科隆，科隆会展中心',
    'lang5': '重启三角洲',
    'lang6': '尊敬的老兵和新兵，',
    'lang7': '我们诚挚地邀请您加入我们的行列，共同重启尘封14年的精英部队。我们期待您的加入，并肩应对危机。让我们携手铸就辉煌，开启新的征程！',
    'lang8': '天',
    'lang9': '小时',
    'lang10': '分钟',
    'lang11': '秒',
    'lang12': '接受任务',
    'lang13': '预约信息',
    'lang14': 'PC',
    'lang15': 'IOS',
    'lang16': '安卓',
    'lang17': '请输入您的邮箱',
    'lang18': '提交',
    'lang19': '点击此处同意',
    'lang20': '隐私条款',
    'lang21': '点击确认我已年满18岁',
    'lang22': '请勾选隐私条款',
    'lang23': '请勾选确认年龄条款',
    'lang24': '邮箱地址有误',
    'lang25': '网络错误，请稍后再试',
    'lang26': '隐私条款',
    'lang27': '关闭',
    'lang28': '预约成功',
    'lang29': '关注Discord官方服务器',
    'lang30': '关注',
    'lang31': '秘密行动-全球召集',
    'lang32': '机密内容',
    'lang33': '任务信息',
    'lang34': '任务细节',
    'lang35': '行动密级',
    'lang36': '机密',
    'lang37': '危险级别',
    'lang38': '中等',
    'lang39': '重要等级',
    'lang40': '极重',
    'lang41': '信息传输中......',
    'lang42': '指挥中心:',
    'lang43': '我们刚通过了你的行动许可，祝你好运！',
    'lang44': '完成本次行动后解锁',
    'lang45': '提交成功',
    'lang46': 'TERMS OF USE',
    'lang47': 'PRIVACY POLICY',
    'lang48': 'COOKIE POLICY',
    'lang49': 'LEGAL NOTICES/OPEN SOURCE',
    'title': '三角洲行动',
    'description': '《三角洲行动》是一款免费的基于特种干员的多玩法第一人称战术射击游戏，将在主机、PC、手游多平台上线。',
    'keywords': 'Delta Force, Delta Force Mobile, Delta Force Mobile, DF Mobile, FPS, esports, team-based gameplay, strategies gameplay, SOL, pro gaming tips, tactical gameplay, class-based, tactical shooter',
    'twitterTitle': 'Reactivate Delta Force',
    'facebookTitle': 'Reactivate Delta Force',
    'twitterDescription': 'Join us in Gamescom 2023 for the grand unveiling of the legacy IP: Delta Force!',
    'facebookDescription': 'Join us in Gamescom 2023 for the grand unveiling of the legacy IP: Delta Force!'
};
console.log(zhLang);
